AWSKEY = "Aasdasd3Q" #s3 key
AWSSECRET = "oIasdsadfjLIM5iMutJXO" #s3 secret
AWSKEYEC = "AKIasdadSA2Q" #ec2 key
AWSSECRETEC = "2asdsad4XyCgO+" #ec2 secret
HOST = "host"
DBUSER = "reomte database user"
DBPASSWORD = "remote database password"
LOCAL_USER = "local user"
LOCAL_PASSWORD = "local password"
PGPASSWORD = "psql pass"
PGHOST = "psql host"
PGUSER = "psql user"
PGDB = "psql db"
PGPORT = "5439"
FABRIC_TABLES=['list','of','tables','fabric']
FEEDBACK_TABLES = ['list','of','tables','feedback']
AMIID= 'ami id'
KEYNAME='key name'
KEYPAIR='keypair name'
SUBNET_ID = 'subnet id'
TAGNAME = "tag for aws instance"
SECURITY_GRP = ['security grp']
RANDOM_MULTIPLIER = 'random_number'
RANDOM_ADD = 'random_number'
DATABASE = 'tt'